### ISSUE TITLE
Clean up Auto-Generated Files

### ISSUE THREAD

**Issue by jkrogers9862** [BioRubeBotProject/Spring_2017#1]
There are a lot of Auto generated files getting into the GitHub, you guys need to clean these up and ideally ensure they don't make it onto the repository.

**Comment by dzsears** [comment]
The auto generated files are in 5 other repositories. Its something we will note for future groups. Maybe their needs to be a procedure that states how to clean the auto generated files. But for now we just followed what the groups before us have done as far as source control goes

**Comment by jkrogers9862** [comment]
There was a solution I put in when I was there, it has since been taken out.

**Comment by dzsears** [comment]
Well we cannot control that good sir. We only followed what was certainly there
